# Generated by Django 3.2.14 on 2022-08-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
