# Generated by Django 3.2.14 on 2022-08-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='lpassword',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='lusername',
        ),
    ]
