# Generated by Django 3.2.14 on 2022-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20220805_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfirstname', models.CharField(max_length=50)),
                ('slastname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=50)),
                ('sphone', models.CharField(max_length=20)),
            ],
        ),
    ]
